Windows Registry Editor Version 5.00

; =========================================================
; CPU — Intel 8ª a 10ª gen (Coffee Lake / Comet Lake)
; =========================================================

; Multiproceso medio, sin P/E cores.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games]
"Affinity"=dword:fffffffe
"ThreadPriority"=dword:00000008
"ThreadAffinity"=dword:0000003e
"ThreadPoolSize"=dword:00000010
"BackgroundThreadPool"=dword:00000004

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel]
"SchedulerAssist"=dword:00000000
"PreferSystemAffinity"=dword:00000001
"ThreadDpcEnable"=dword:00000001