Windows Registry Editor Version 5.00

; =========================================================
; GPU — NVIDIA RTX 30 series (Ampere)
; =========================================================

; HAGS activo (mejora latencia en Ampere).
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"HwSchMode"=dword:00000002

; Desactivar MPO: reduce flickering y micro-stutter en Ampere.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"DisableMPO"=dword:00000001
"AllowTearingInDWM"=dword:00000001

; Shader cache grande.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectX]
"ShaderCacheSize"=dword:00000a00